version: '3.9'

services:
 
  app3:
    build: .
    container_name: app3
    hostname: app3.dev.sonia.de
    restart: always
    volumes:
      - ./html:/var/www/html:ro
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8083:80"

networks:
  default:
    name: iddev
    external: true
