version: '3.9'

services:
 
  app10:
    image: bellsoft/liberica-openjdk-alpine:17
    container_name: app10
    hostname: app10.dev.sonia.de
    restart: always
    command: "/workspace/entrypoint.sh"
    volumes:
      - .:/workspace
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8090:8090"

  app10sfront:
    image: nginx:1
    container_name: app10sfront
    hostname: app10s.dev.sonia.de
    restart: always
    ports:
      - "8490:443"
    volumes:
      - ./nginx/etc:/etc/nginx
      - ./nginx/cache:/share/container/nginx/cache
      - ./nginx/log:/var/log/nginx
    environment:
      - TZ=Europe/Berlin

networks:
  default:
    name: iddev
    external: true
