version: '3.9'

services:
 
  app13:
    image: golang:1.21.6
    container_name: app13
    hostname: app13.dev.sonia.de
    restart: always
    command: "/workspace/entrypoint.sh"
    volumes:
      - .:/workspace
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8093:8093"

networks:
  default:
    name: iddev
    external: true
